CREATE TABLE IF NOT EXISTS `TB` 
(
    'id' INTEGER PRIMARY KEY AUTOINCREMENT,
    'radius_mean': 'FLOAT DEFAULT NULL',
    'texture_mean': 'FLOAT DEFAULT NULL',
    'perimeter_mean': 'FLOAT DEFAULT NULL',
    'area_mean': 'FLOAT NOT NULL',
    'smoothness_mean': 'FLOAT DEFAULT NULL',
    'compactness_mean': 'FLOAT DEFAULT NULL',
    'concavity_mean': 'FLOAT DEFAULT NULL',
    'concave points_mean': 'FLOAT DEFAULT NULL',
    'symmetry_mean': 'FLOAT DEFAULT NULL',
    'fractal_dimension_mean': 'FLOAT DEFAULT NULL',
    'radius_se': 'FLOAT DEFAULT NULL',
    'texture_se': 'FLOAT DEFAULT NULL',
    'perimeter_se': 'FLOAT DEFAULT NULL',
    'area_se': 'FLOAT DEFAULT NULL',
    'smoothness_se': 'FLOAT DEFAULT NULL',
    'compactness_se': 'FLOAT DEFAULT NULL',
    'concavity_se': 'FLOAT DEFAULT NULL',
    'concave points_se': 'FLOAT DEFAULT NULL',
    'symmetry_se': 'FLOAT DEFAULT NULL',
    'fractal_dimension_se': 'FLOAT DEFAULT NULL',
    'radius_worst': 'FLOAT DEFAULT NULL',
    'texture_worst': 'FLOAT DEFAULT NULL',
    'perimeter_worst': 'FLOAT DEFAULT NULL',
    'area_worst': 'FLOAT DEFAULT NULL',
    'smoothness_worst': 'FLOAT DEFAULT NULL',
    'diagnosis': 'VARCHAR(2) DEFAULT NULL',
    PRIMARY KEY (`id`)
)
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_unicode_ci;